# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtt < Formula
  desc "Git worktree manager — create, navigate, and remove worktrees easily"
  homepage "https://github.com/songtov/wtt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_darwin_amd64.tar.gz"
      sha256 "f06b5a4a705541055186483a6dbc97086ac29be1b324c36e729dcb576a1beaf0"

      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_darwin_arm64.tar.gz"
      sha256 "ab2bd9e92bc38d4829e7b748d3e8d5f7bf2fb36c77f9ea8967d20e6037aac5fb"

      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_linux_amd64.tar.gz"
      sha256 "111d5b919d3e3b72aaf9a5314c07cba29f4cea13a5b1aff6ccb5c0c738862eeb"
      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_linux_arm64.tar.gz"
      sha256 "215bb3aaeb993b534f90d3ed23e5dc6196e0c54e3be1b2abb7116469554e3704"
      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell navigation (cd on worktree select), add this to your shell rc:

        # zsh (~/.zshrc):
        eval "$(wtt-bin --init zsh)"

        # bash (~/.bashrc or ~/.bash_profile):
        eval "$(wtt-bin --init bash)"

        # fish (~/.config/fish/config.fish):
        wtt-bin --init fish | source
    EOS
  end
end
