# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtt < Formula
  desc "Git worktree manager — create, navigate, and remove worktrees easily"
  homepage "https://github.com/songtov/wtt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_darwin_amd64.tar.gz"
      sha256 "77a1428f16002b517497189cf5940c1f3d665bbf9354d8ca58520b0bb527463e"

      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_darwin_arm64.tar.gz"
      sha256 "f141732878edf71c519b6defa023a67bbf5e42bc14158932fa9d2114306d79c9"

      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_linux_amd64.tar.gz"
      sha256 "d24b30d7f2cd3b3bdcae2225e84364a5fac1b5d39372e122cb85053ec2a871ed"
      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/songtov/wtt/releases/download/v0.1.0/wtt_linux_arm64.tar.gz"
      sha256 "11953c120e49fdfcd3313913dd2963fe6229dacff36de797b4659ae12168c7ab"
      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell navigation (cd on worktree select), add this to your shell rc:

        # zsh (~/.zshrc):
        eval "$(wtt-bin --init zsh)"

        # bash (~/.bashrc or ~/.bash_profile):
        eval "$(wtt-bin --init bash)"

        # fish (~/.config/fish/config.fish):
        wtt-bin --init fish | source
    EOS
  end
end
