# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtt < Formula
  desc "Git worktree manager — create, navigate, and remove worktrees easily"
  homepage "https://github.com/songtov/wtt"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/songtov/wtt/releases/download/v0.3.0/wtt_darwin_amd64.tar.gz"
      sha256 "ae9be372c3596c87311b5def78e954d50a509759c2241418a0bb17a428169b11"

      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/songtov/wtt/releases/download/v0.3.0/wtt_darwin_arm64.tar.gz"
      sha256 "61a7be07b16eea52178ffa9bfb74e62ee7da55ad3fca3cabad3c0926b9090569"

      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/songtov/wtt/releases/download/v0.3.0/wtt_linux_amd64.tar.gz"
      sha256 "a312c3df88bd2c0ab034cc60f6785ee85bbc994d2e787ee724ea93d1db5ebf19"
      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/songtov/wtt/releases/download/v0.3.0/wtt_linux_arm64.tar.gz"
      sha256 "98adb97add0df9d7186f22c737f855dedd5a0afabb42bcbbe865f17a0941480c"
      define_method(:install) do
        bin.install "wtt-bin"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell navigation (cd on worktree select), add this to your shell rc:

        # zsh (~/.zshrc):
        eval "$(wtt-bin --init zsh)"

        # bash (~/.bashrc or ~/.bash_profile):
        eval "$(wtt-bin --init bash)"

        # fish (~/.config/fish/config.fish):
        wtt-bin --init fish | source
    EOS
  end
end
